# true colors?
set-option -sa terminal-overrides ",xterm*:Tc"

# use the mouse, change panes by clicking and scroll through the buffer
set -g mouse on

# start index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# bind `Shift + Enter` to be `Ctrl + J` which the terminal standard for inserting a newline
#bind -n S-Enter send-keys C-j
# fancier way to do the above
set -s extended-keys on 
set -as terminal-features 'xterm*:extkeys'

# reload config
bind r source-file ${HOME}/.config/tmux/tmux.conf \; display-message "source-file reloaded"
# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
run $HOME/.config/tmux/plugins/tpm/tpm
