
# use the mouse, change panes by clicking and scroll through the buffer
set -g mouse on

# start index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Recognize modified keys from the terminal, then map Shift+Enter to Ctrl+J
# for newline insertion in terminal application prompts.
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
bind -n S-Enter send-keys C-j

# true colors?
set-option -sa terminal-overrides ",xterm*:Tc"

# reload config
bind r source-file ${HOME}/.config/tmux/tmux.conf \; display-message "source-file reloaded"
# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
run $HOME/.config/tmux/plugins/tpm/tpm
